In [2]:
import numpy as np

a= np.matrix('1 2 3;4 5 6')
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(a)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [3]:
print(a[1,:])

[[4 5 6]]


In [4]:
print(a[:,2])

[[3]
 [6]]


In [20]:
# if we need to print rows
print(a[:,0:2])

[[1 2]
 [4 5]]


In [4]:
print(a[:,2])

[[3]
 [6]]


In [5]:
#print the 1st row 2nd element.
print(a[0,1])

2


### Order of the matrix

In [6]:
print(a.shape)

(2, 3)


### Matrix Operations

In [7]:
a=np.matrix('1 1;2 43')
b=np.matrix('1 4;1 32')
print(a+b)

[[ 2  5]
 [ 3 75]]


#### Scalar Multiplication

In [8]:
a=np.matrix('2 1;2 2;3 3')
a
print(4*a)

[[ 8  4]
 [ 8  8]
 [12 12]]


#### Matrix Multiplication

In [9]:
a=np.matrix('1 2 3;4 5 6')
b=np.matrix('2 4 5;2 45 6;2 1 6')
c=a*b
print(c)

[[ 12  97  35]
 [ 30 247  86]]


### Determinant of the Matrices

In [10]:
a=np.matrix('1 4 6;87 0 3;2 58 54')
b=np.linalg.det(a)
print(b)

11334.0


In [11]:
a=np.matrix('2 4 6;2 43 56;2 3 54')
b=np.linalg.det(a)
print(b)

3844.000000000001


### Transpose of Matrix

In [3]:
a=np.matrix('2 4 6;2 43 56;2 3 54')
b=np.matrix.transpose(a)
print(b)

[[ 2  2  2]
 [ 4 43  3]
 [ 6 56 54]]


### Inverse of the Matrix

In [13]:
a=np.matrix('1 2 5;0 8 0;7 6 1')
y=np.linalg.inv(a)
print(y)
a

[[-0.02941176 -0.10294118  0.14705882]
 [ 0.          0.125       0.        ]
 [ 0.20588235 -0.02941176 -0.02941176]]


matrix([[1, 2, 5],
        [0, 8, 0],
        [7, 6, 1]])

In [14]:
import numpy as num

a=num.matrix('3 -1 1;2 1 0;1 2 -1')
b=num.matrix('2;1;3')

c=num.linalg.inv(a)

print(c*b)

[[ 2.]
 [-3.]
 [-7.]]


In [17]:
a=num.matrix('3 -1 1;2 1 0;1 2 -1')
b=num.matrix('2;1;3')

c=num.linalg.solve(a,b)

print(c)

[[ 2.]
 [-3.]
 [-7.]]


In [35]:
r=np.matrix('2 3 4;2 4 5;2,4,6')
#r=np.array([[2,3,4],[2,4,5],[2,4,6]])
print(r)

[[2 3 4]
 [2 4 5]
 [2 4 6]]


In [36]:
np.linalg.inv(r)

matrix([[ 2. , -1. , -0.5],
        [-1. ,  2. , -1. ],
        [ 0. , -1. ,  1. ]])

In [37]:
np.linalg.det(r)

2.0