In [2]:
import numpy as np

a= np.matrix('1 2 3;4 5 6')
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(a)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [3]:
# if we need to print rows
print(a[1,:])

[[4 5 6]]


In [10]:
print(a[:,-2])

[[2]
 [5]]


In [5]:
#print the 1st row 2nd element.
print(a[0,1])

2


### Order of the matrix

In [6]:
print(a.shape)

(2, 3)


### Matrix Operations

In [7]:
a=np.matrix('1 1;2 43')
b=np.matrix('1 4;1 32')
print(a+b)

[[ 2  5]
 [ 3 75]]


In [ ]:
# SCalar multiplication

#### Scalar Multiplication

In [8]:
a=np.matrix('2 1;2 2;3 3')
a
print(4*a)

[[ 8  4]
 [ 8  8]
 [12 12]]


#### Matrix Multiplication

In [9]:
a=np.matrix('1 2 3;4 5 6')
b=np.matrix('2 4 5;2 45 6;2 1 6')
c=a*b
print(c)

[[ 12  97  35]
 [ 30 247  86]]


### Transpose of Matrix

In [12]:
a=np.matrix('2 4 6;2 43 56;2 3 54')
b=np.matrix.transpose(a)
print(b)

[[ 2  2  2]
 [ 4 43  3]
 [ 6 56 54]]
