# Vectors

In [1]:
import numpy as np 

lst = [10,20,30,40,50] 

vctr = np.array(lst) 

print("Vector created from a list:") 
print(vctr)

Vector created from a list:
[10 20 30 40 50]


In [2]:
vctr = np.array('10,20,30,40,50') 
print(vctr)

10,20,30,40,50


In [3]:
vctr = np.array([10,20,30,40,50]) 
print(vctr)

[10 20 30 40 50]


In [4]:
import numpy as np 

lst = [[2], 
        [4], 
        [6],
          [10]]  

vctr = np.array(lst) 

print("Vector created from a list:") 
print(vctr)

Vector created from a list:
[[ 2]
 [ 4]
 [ 6]
 [10]]


### Basic Operations

In [5]:
import numpy as np 

lst1 = [10,20,30,40,50] 
lst2 = [1,2,3,4,5]
vctr1 = np.array(lst1) 
vctr2= np.array(lst2) 
print(vctr1)  
print(vctr2) 
vctr_add = vctr1+vctr2
print("Addition of two vectors: ",vctr_add)

[10 20 30 40 50]
[1 2 3 4 5]
Addition of two vectors:  [11 22 33 44 55]


In [6]:
import numpy as np 

lst1 = [10,20,30,40,50] 
lst2 = [1,2,3,4,5]

vctr1 = np.array(lst1) 

vctr2= np.array(lst2) 

vctr_sub = vctr1-vctr2
print("Subtraction of two vectors: ",vctr_sub)

Subtraction of two vectors:  [ 9 18 27 36 45]


In [7]:
import numpy as np 
 
lst1 = [10,20,30,40,50] 
lst2 = [10,20,30,40,50]
 
vctr1 = np.array(lst1) 
 
vctr2= np.array(lst2) 

vctr_div = vctr1/vctr2
print("Division of two vectors: ",vctr_div)

Division of two vectors:  [1. 1. 1. 1. 1.]


#### Vector dot product

In [10]:
import numpy as np 

lst1 = [10,20,30,40,50] 
lst2 = [1,1,1,1,1]


vctr1 = np.array(lst1) 

vctr2= np.array(lst2) 

#vctr_dot = vctr1.dot(vctr2)
vctr_dot= np.dot(vctr1,vctr2)
print("Dot product of two vectors: ",vctr_dot)

Dot product of two vectors:  150


### Magnitude of a Vector

#### Method 01:Use linalg.norm()

In [9]:
import numpy as np

#define vector
x = np.array([3, 6, 6, 4, 8, 12, 13])

#calculate magnitude of vector
np.linalg.norm(x)

21.77154105707724

Method to find the magnitude

#### Method 02: Use Custom NumPy Functions

In [10]:
#define vector
x = np.array([3, 6, 6, 4, 8, 12, 13])

#calculate magnitude of vector
np.sqrt(x.dot(x))


21.77154105707724

In [ ]:
np.sqrt(np.dot(x,x))

### Unit Vectors

#### Method 1: Using unit_vector() method from transformations library

In [5]:
pip install transformations

Note: you may need to restart the kernel to use updated packages.


In [11]:
import transformations as tr
# creating a numpy array
arr = np.array([1,2,3])
# normalizing the array to unit vector
#print(transformations.unit_vector(arr))
print(tr.unit_vector(arr))

[0.26726124 0.53452248 0.80178373]


In [4]:
3/np.sqrt(14)

0.8017837257372732

#### Method 2: Using normalize() method from vg module.

In [8]:
pip install vg

Note: you may need to restart the kernel to use updated packages.


In [3]:
import vg
# creating a numpy array
arr = np.array([1,2,3])
# normalizing the array to unit vector
unit_vector = vg.normalize(arr)
print(unit_vector)

[0.26726124 0.53452248 0.80178373]


#### Method 3: Using linalg.norm() method from numpy module

In [17]:
import numpy as np
data = np.array([1,2,3])
# normalizing the array to unit vector
unitVector = data / np.linalg.norm(data)
print(unitVector)

[0.26726124 0.53452248 0.80178373]


### Product of Vectors

In [7]:

p = [4, 2]
q = [5, 6]
product = np.cross(p,q)
print(product)

14


In [8]:
p = np.array ([1,2])
q = np.array ([1,3])
product = np.cross(p,q)
print(product)

1


In [22]:
arr1 = np.array([2,2])
arr2 = np.array([5,10])
dotproduct = np.dot(arr1, arr2)
print("Dot product of two array is:", dotproduct)

Dot product of two array is: 30
